### ISSUE TITLE
An issue on orientation.isFlat

### ISSUE THREAD

**Issue by Appicus** [ink-spot/UPCarouselFlowLayout#1]
When device changes its orientation from orientation.isPortrait / orientation.isLandcape to orientation.isFlat there should not be any changes:

  @objc private func rotationDidChange() {
    if orientation.isFlat {
      print("orientation.isFlat - Do not change anything")
      return
    }
    let layout = self.collectionView.collectionViewLayout as! SIKUCarouselFlowLayout
    let direction: UICollectionViewScrollDirection = orientation.isPortrait ? .horizontal : .vertical
    layout.scrollDirection = direction
    if currentPage > 0 {
      let indexPath = IndexPath(item: currentPage, section: 0)
      let scrollPosition: UICollectionViewScrollPosition = UIDeviceOrientationIsPortrait(orientation) ? .centeredHorizontally : .centeredVertically
      self.collectionView.scrollToItem(at: indexPath, at: scrollPosition, animated: false)
    }
  }

**Comment by ink-spot** [comment]
Thanks for your feedback.
It's not very important since it's only in the demo app, but I added it anyway: https://github.com/ink-spot/UPCarouselFlowLayout/commit/74415478403e88dc56acfa9c8d59e2b8825fd16c
