### ISSUE TITLE
Paging does not page to the center of an item as would be expected

### ISSUE THREAD

**Issue by cjhenck** [ink-spot/UPCarouselFlowLayout#12]
If you enable paging on the UICollectionView it does not scroll to a specific item and will instead end up between items.

I need to test more to confirm in a clean project.

**Comment by niteshtak** [comment]
Yeah can you please fix that why its not paginated properly.

**Comment by itruf** [comment]
You should turn off pagination in uicollectionview if it's enabled.

**Comment by cjhenck** [comment]
This isn't really a solution - pagination is an ideal use case for this library if you want to force people to go through cells one at a time.  I think the solution is to set the size perfectly for a single page if paging is enabled.

**Comment by ink-spot** [comment]
This layout isn't supposed to work with the paging enabled, as it replaces the pagination logic to "squeeze" the expected page size to let the side items appear.
If you set the collection size to fit a single page, you won't be able to see those items, or if you set the `clipToBounds` to `false` you won't be able to scroll the collection from its sides.
