### ISSUE TITLE
Layout attribute

### ISSUE THREAD

**Issue by andreyoshev** [ink-spot/UPCarouselFlowLayout#13]
Layout attribute works not fine.

![img_8114](https://cloud.githubusercontent.com/assets/17673010/20340673/97aa5980-ac04-11e6-88ab-c3ac89c5d49e.PNG)

When u scroll next - everything alright.

**Comment by mboeddeker** [comment]
Same here!

**Comment by andreyoshev** [comment]
@mboeddeker iOS 10... w/o all cell's data same..

**Comment by andreyoshev** [comment]
@mboeddeker I fixed that.

if #available(iOS 10.0, *) { collectionView.prefetchingEnabled = false }

**Comment by ink-spot** [comment]
Indeed, it seemed to be related to the prefetching of the collectionView.
Thanks @andreyoshev for pointing this out and for the fix 👍
