### ISSUE TITLE
iOS 7 and iOS 8

### ISSUE THREAD

**Issue by pjebs** [ink-spot/UPCarouselFlowLayout#2]
I noticed that it is supported by only iOS8.1+

What part of the code makes it not work with iOS 7?

**Comment by Appicus** [comment]
If you set Deployment Target to 7.0 there is an issue with Alerts, but if you fix that it should be working fine.

**Comment by pjebs** [comment]
I did a search in `UPCarouselFlowLayout.swift` and don't see any mention of 'Alerts'?

**Comment by Appicus** [comment]
You asked what part of code makes it not work with iOS 7.0 Look at ViewController.swift in Function:

    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let character = items[(indexPath as NSIndexPath).row]
        let alert = UIAlertController(title: character.name, message: nil, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
        present(alert, animated: true, completion: nil)
    }

In iOS 7.0 you cannot use UIAlertController like this. You need to fix this in order to compile with deployment target 7.0

**Comment by pjebs** [comment]
Oh okay - Thanks. Just miscommunication. I was referring to the actual code and you were referring to the example project.
