### ISSUE TITLE
Glitch - programmatically approach

### ISSUE THREAD

**Issue by makiboy23** [ink-spot/UPCarouselFlowLayout#21]
Hi, 

**

> Glitch - programmatically approach

**
Can you help me to resolve this problem? When the numberOfItemsInSection exceeded in 4 the Glitch was happening. Kindly see my attached picture that show the Glitch.
![screen shot 2017-04-27 at 3 07 58 pm](https://cloud.githubusercontent.com/assets/5186993/25472180/b83568a2-2b5c-11e7-9147-04be9e0ef3f2.png)

Here's my code:
![screen shot 2017-04-27 at 3 19 26 pm](https://cloud.githubusercontent.com/assets/5186993/25472220/f12c9824-2b5c-11e7-86cb-eae8c37cad28.png)

and Project Navigation :
![screen shot 2017-04-27 at 3 20 19 pm](https://cloud.githubusercontent.com/assets/5186993/25472241/0db88d2c-2b5d-11e7-892e-f34dc18f75c1.png)

**Comment by BumwooPark** [comment]
i have same issue too

**Comment by madhusamuel** [comment]
We've the same issue.

**Comment by nikechanhk** [comment]
Hi all,

I just found the solution.

In the storyboard/XIB, "untick" the Prefetch check box.
![slider_bug_fix](https://cloud.githubusercontent.com/assets/25634967/26530221/49d55132-4403-11e7-8885-e44d02b44626.png)

**Comment by nikechanhk** [comment]
@ink-spot 
Since start from ios 10, "Prefetching" default is set to be true, I suggest mention it in the documentation.
