### ISSUE TITLE
Circlular

### ISSUE THREAD

**Issue by pjebs** [ink-spot/UPCarouselFlowLayout#3]
I was wondering if there was some way to make the control operate like this:

https://github.com/awdigital/AWCollectionViewDialLayout

**Comment by ink-spot** [comment]
Actually, that's not how I designed this layout so I don't plan to do it, but you can certainly try to implement it.
I guess the starting point would be to tweak the origin/transform of the items attributes in the `transformLayoutAttributes` method of the layout (alongside the scale and opacity tweaks already there).
