### ISSUE TITLE
Disable Transform

### ISSUE THREAD

**Issue by B-Rass** [ink-spot/UPCarouselFlowLayout#4]
Hi !

First thanks for sharing your great work :)

I need to disable the sideScale transform on some part / view of my cell. 
Do you see a way to do it ?

Cheers !

**Comment by almazini** [comment]
> sideItemScale (between 0 and 1, default is 0.6) Can be set through code or via Interface Builder. The shrinking ratio for collection items which are not in the center.

**Comment by B-Rass** [comment]
Yes but sideItemScale is scaling every subviews and elements of the cell. And I would need to disable the scaling effect on one of my cell's subviews.
