### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by B-Rass** [ink-spot/UPCarouselFlowLayout#9]
Hi !

I would like to know if you planned to create a swift 3-compatible version of your work ? Thanks :)

**Comment by niazoff** [comment]
Any news?

**Comment by kostapappas** [comment]
use the following until he update the pod's
pod 'UPCarouselFlowLayout', :git => 'https://github.com/ink-spot/UPCarouselFlowLayout.git'

**Comment by ink-spot** [comment]
Hey, the pod has finally been updated to version `1.1.1`, which is in Swift 3.
